Improvements to the init scripts
Checks more error conditions, cleans up the console redirect mess somewhat, does more from the real root

diff --git a/ramdisk/common/init b/ramdisk/common/init
--- a/ramdisk/common/init
+++ b/ramdisk/common/init
@@ -1,106 +1,92 @@
 #!/bin/sh
 
 ROOTIMG=/sdcard/root.img
-
 DEBUG=1
-COMPCACHE=1
 
-mount -t proc none /proc
-mount -t sysfs none /sys
+if [ ! "$INITIALDONE" = "1" ]
+then
+	mount -t proc none /proc
+	mount -t sysfs none /sys
 
-mount -t devtmpfs devtmpfs /dev
-mkdir -m 0755 /dev/pts
-mkdir /dev/pts
-mount -t devpts -o gid=5,mode=620 devpts /dev/pts
+	mount -t devtmpfs devtmpfs /dev
+	mkdir -m 0755 /dev/pts
+	mkdir /dev/pts
+	mount -t devpts -o gid=5,mode=620 devpts /dev/pts
 
-echo /sbin/axdroid_hotplug > /proc/sys/kernel/hotplug
+	INITIALDONE=1 exec /init >/dev/console 2>&1
+fi
 
 hang()
 {
+	echo "Unable to proceed - hanging..."
+
+	echo "Mountpoints:"
+	mount
+
+	echo "Root:"
+	ls /
+
 	while [ true ]
 	do
 		echo >/dev/null
 	done
 }
 
-echo "Axdroid booting..." > /dev/console
-cat /proc/cpuinfo > /dev/console
+cpRd2Rt()
+{
+	RDPATH=/$1
+	RTPATH=/realroot/$1
 
-echo "Mountpoints:" >/dev/console
-mount >/dev/console 2>&1
+	if [ ! -d $RDPATH ]
+	then
+		echo "WARNING: RD path '$RDPATH' doesn't exist"
+		return 0
+	fi
 
-echo "/:" >/dev/console
-ls -l / >/dev/console 2>&1
+	mkdir -p $RTPATH
+	[ ! $? -eq 0 ] && echo "Unable to mkdir $RTPATH" && hang
 
-if [ $COMPCACHE -eq 1 ]
-then
-	insmod /lib/modules/ramzswap.ko num_devices=1
-fi
+	cp -a $RDPATH/* $RTPATH/
+	[ ! $? -eq 0 ] && echo "Unable to cp $RDPATH to root" && hang
+}
+
+mntRd2Rt()
+{
+	RDPATH=/$1
+
+	if [ $# -gt 1]
+	then
+		RTPATH=/realroot/$2
+	else
+		RTPATH=/realroot/$1
+	fi
+
+	mkdir -p $RTPATH
+	[ ! $? -eq 0 ] && echo "Unable to mkdir $RTPATH" && hang
+
+	mount -o move $RDPATH $RTPATH
+	[ ! $? -eq 0 ] && echo "Unable to move mount $RDPATH to root" && hang
+}
+
+echo "Axdroid booting..."
 
 mkdir /sdcard
-mount -t vfat -o async,noatime,nodiratime,umask=0000 /dev/mmcblk0p1 /sdcard > /dev/console 2>&1
+mount -t vfat -o async,noatime,nodiratime,umask=0000 /dev/mmcblk0p1 /sdcard
+[ ! $? -eq 0 ] && echo "Unable to mount SD card!" && hang
 
-if [ ! $? -eq 0 ]
-then
-	echo "Unable to mount SD card!"
-	echo "mount: exit status $?"
-	hang
-fi
-
-echo "SD card mounted" > /dev/console
-ls /sdcard > /dev/console
-
-echo "Mounting root FS image" > /dev/console
 mkdir /realroot
-mount -o loop,noatime,nodiratime $ROOTIMG /realroot > /dev/console 2>&1
+mount -o loop,noatime,nodiratime $ROOTIMG /realroot
+[ ! $? -eq 0 ] && echo "Unable to mount root FS!" && hang
 
-if [ ! $? -eq 0 ]
-then
-	echo "Unable to mount root FS image!"
-	echo "mount: exit status $?"
-	hang
-fi
+cpRd2Rt bin
+cpRd2Rt sbin
+cpRd2Rt usr/bin
+cpRd2Rt usr/sbin
 
-mkdir -p /realroot/bin
-mkdir -p /realroot/sbin
-mkdir -p /realroot/usr/bin
-mkdir -p /realroot/usr/sbin
-mkdir -p /realroot/lib/modules
-cp -a /bin/* /realroot/bin/ > /dev/console 2>&1
-cp -a /sbin/* /realroot/sbin/ > /dev/console 2>&1
-cp -a /usr/bin/* /realroot/usr/bin/ > /dev/console 2>&1
-cp -a /usr/sbin/* /realroot/usr/sbin/ > /dev/console 2>&1
-cp -a /lib/modules/* /realroot/lib/modules/ > /dev/console 2>&1
+mntRd2Rt proc
+mntRd2Rt sys
+mntRd2Rt dev
+mntRd2Rt sdcard mnt/sdcard
 
-if [ $DEBUG -eq 0 ]
-then
-	VGA=`cat /proc/mtd | grep "Video SDRAM" | wc -l`
-	if [ $VGA -eq 1 ]
-	then
-		cp /initlogoVGA.rle /realroot/initlogo.rle
-	else
-		cp /initlogoQVGA.rle /realroot/initlogo.rle
-	fi
-else
-	rm -f /realroot/initlogo.rle
-fi
-
-echo "/realroot:" > /dev/console
-ls -l /realroot > /dev/console
-#sleep 5s
-
-echo "/realroot/bin:" > /dev/console
-ls /realroot/bin > /dev/console
-
-echo "Moving system mountpoints" > /dev/console
-mount -o move /proc /realroot/proc
-mount -o move /sys /realroot/sys
-mount -o move /dev /realroot/dev
-
-echo "Moving SD card mountpoint" > /realroot/dev/console
-mkdir -p /realroot/mnt/sdcard
-mount -o move /sdcard /realroot/mnt/sdcard
-
-echo "Switching root" > /realroot/dev/console
 exec switch_root -c /dev/console /realroot /axdroid.sh
 
